[profile.default]
src = 'contracts'
out = 'foundry_out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
gas_reports = ["RoninValidatorSet"]

[rpc_endpoints]
devnet = "${DEVNET_URL}"
